### ISSUE TITLE
Failed to run the demo.py after loading the trakcing model network

### ISSUE THREAD

**Issue by gupork** [MVIG-SJTU/AlphAction#1]
Thank you for your great sharing! I succeed to download and install, however after starting the command on running the demo.py:
python demo.py --video-path test_F.mp4 --output-path ../data/output/output.mp4 --cfg-path ../data/config/resnet101_8x8f_denseserial.yaml --weight-path ../data/models/common_15cat_res101.pth --common-cate 

The output fail to run further and the terminal output as below:
Starting video demo, video path: test_F.mp4
Loading YOLO model..
Network successfully loaded
Loading tracking model..
0it [00:00, ?it/s]Network successfully loaded
2331it [09:27,  3.20it/s]Traceback (most recent call last):
  File "demo.py", line 173, in <module>
    main()
  File "demo.py", line 136, in main
    (orig_img, boxes, scores, ids) = ava_predictor_worker.read_track()
  File "/home/user/AlphAction/demo/action_predictor.py", line 260, in read_track
    return self.track_queue.get()
  File "/home/user/anaconda3/envs/action_det/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/user/anaconda3/envs/action_det/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/user/anaconda3/envs/action_det/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/user/anaconda3/envs/action_det/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/user/anaconda3/envs/action_det/lib/python3.7/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata
2331it [09:28,  4.10it/s]

Can provide me some direction to solve it? Many thanks!

**Comment by yelantf** [comment]
Sorry for the late reply, we updated the code just now. Please use the newest version to check if this bug still exists.

**Comment by uname0x96** [comment]
@yelantingfeng Thanks for your work. Can you public the tranning code?

**Comment by yelantf** [comment]
@cong235 Yes, the training code with pre-trained weights will be made public later.

**Comment by gupork** [comment]
> Sorry for the late reply, we updated the code just now. Please use the newest version to check if this bug still exists.

Thanks @yelantingfeng , I downloaded your latest version and it works now! Look forward to your training code.

**Comment by uname0x96** [comment]
@yelantingfeng I try to check the performance of your project. 
This is the result:
Card: GTX-2080ti
FPS: 20
GPU-ram: 6.5gb
Mem: 10gb
It's heavy. Is it the same as your result?

**Comment by yelantf** [comment]
> @yelantingfeng I try to check the performance of your project.
> This is the result:
> Card: GTX-2080ti
> FPS: 20
> GPU-ram: 6.5gb
> Mem: 10gb
> It's heavy. Is it the same as your result?

Yes, the memory occupation of GPU and CPU above are both reasonable since we need to construct a tracking model and an action detection model. This may be heavy for personal devices, but should be acceptable for most servers.

**Comment by dongfangduoshou123** [comment]
python demo.py --webcam --output-path ./out/test.mp4 --cfg-path ../config_files/resnet101_8x8f_denseserial.yaml --weight-path ../data/models/aia_models/resnet101_8x8f_denseserial.pth --common_cate
pydev debugger: process 17419 is connecting
Connected to pydev debugger (build 201.6668.115)
Starting webcam demo, press Ctrl + C to terminate...
Loading YOLO model..
Network successfully loaded
Traceback (most recent call last):
  File "/home/wzq/Downloads/pycharm-community-2020.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wzq/Downloads/pycharm-community-2020.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/demo/demo.py", line 186, in <module>
    main()
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/demo/demo.py", line 144, in main
    ava_predictor_worker = AVAPredictorWorker(args)
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/demo/action_predictor.py", line 189, in __init__
    cfg.device,
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/demo/action_predictor.py", line 62, in __init__
    _ = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/AlphAction/utils/checkpoint.py", line 61, in load
    self._load_model(checkpoint, no_head)
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/AlphAction/utils/checkpoint.py", line 110, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"), no_head)
  File "/media/wzq/Seagate/ubuntu1604/AlphaPoseProject/AlphAction/AlphAction/utils/model_serialization.py", line 83, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/wzq/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ActionDetector:
	size mismatch for roi_heads.action.predictor.cls_score.weight: copying a param with shape torch.Size([80, 1024]) from checkpoint, the shape in current model is torch.Size([15, 1024]).
	size mismatch for roi_heads.action.predictor.cls_score.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([15]).


@yelantingfeng 您好，我遇到了类似的问题，但又不一样，帮忙看下，谢谢！

**Comment by yelantf** [comment]
@dongfangduoshou123 你使用了错误的权重，如果使用--common_cate参数，需要使用对应的常见类别模型`common_15cat_res101.pth`（ https://drive.google.com/open?id=1CudK8w0d2_5r73_tnyAY1Fnwd78hce3M ），该链接在demo中的README里有提供。
