### ISSUE TITLE
When I test the Model ,I got this error. 

### ISSUE THREAD

**Issue by zhaoleo1111** [MVIG-SJTU/AlphAction#24]
Traceback (most recent call last):
  File "test_net.py", line 8, in <module>
    from alphaction.modeling.detector import build_detection_model
  File "/home/leo/AlphAction/alphaction/modeling/detector/__init__.py", line 1, in <module>
    from .action_detector import build_detection_model
  File "/home/leo/AlphAction/alphaction/modeling/detector/action_detector.py", line 3, in <module>
    from ..backbone import build_backbone
  File "/home/leo/AlphAction/alphaction/modeling/backbone/__init__.py", line 1, in <module>
    from .backbone import build_backbone
  File "/home/leo/AlphAction/alphaction/modeling/backbone/backbone.py", line 2, in <module>
    from . import slowfast, i3d
  File "/home/leo/AlphAction/alphaction/modeling/backbone/slowfast.py", line 6, in <module>
    from alphaction.modeling.common_blocks import ResNLBlock
  File "/home/leo/AlphAction/alphaction/modeling/common_blocks.py", line 2, in <module>
    from alphaction.modeling.nonlocal_block import NLBlock
  File "/home/leo/AlphAction/alphaction/modeling/nonlocal_block.py", line 6, in <module>
    from alphaction.layers import FrozenBatchNorm3d
  File "/home/leo/AlphAction/alphaction/layers/__init__.py", line 3, in <module>
    from .roi_align_3d import ROIAlign3d
  File "/home/leo/AlphAction/alphaction/layers/roi_align_3d.py", line 7, in <module>
    import alphaction._custom_cuda_ext as _C
ModuleNotFoundError: No module named 'alphaction._custom_cuda_ext'
Traceback (most recent call last):
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/leo/anaconda3/envs/mmaction2/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/leo/anaconda3/envs/mmaction2/bin/python', '-u', 'test_net.py', '--local_rank=0', '--config-file', 'config_files/resnet50_4x16f_baseline.yaml', 'MODEL.WEIGHT', 'Models/resnet50_4x16f_baseline.pth']' returned non-zero exit status 1.

**Comment by yelantf** [comment]
Please make sure that you have cloned the newest version and successfully installed the project strictly following [INSTALL.md](../blob/master/INSTALL.md). Also, you may refer to #10 for some potentially helpful information.

**Comment by yelantf** [comment]
Issue closed due to the lack of response.
