### ISSUE TITLE
How to install AlphAction without cuda?

### ISSUE THREAD

**Issue by universewill** [MVIG-SJTU/AlphAction#29]
I want to use alphAction on my macbook pro.
And get errors when run command 'pip install -e .'
The error is as follow:
```
Obtaining file:///Users/u/project/AlphAction
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Compiling detector/nms/src/soft_nms_cpu.pyx because it changed.
    [1/1] Cythonizing detector/nms/src/soft_nms_cpu.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/u/project/AlphAction/setup.py", line 107, in <module>
        ext_modules=get_extensions(),
      File "/Users/u/project/AlphAction/setup.py", line 92, in get_extensions
        sources=['src/nms_cpu.cpp']),
      File "/Users/u/project/AlphAction/setup.py", line 42, in make_cuda_ext
        '-D__CUDA_NO_HALF2_OPERATORS__',
      File "/Users/u/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 779, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/Users/u/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 869, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/Users/u/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1783, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /Users/u/project/AlphAction/

```

**Comment by yelantf** [comment]
Sorry, we only plan to support GPU for this project. The computation cost could be much heavy for CPU devices or even laptops with a nvidia GPU (see https://github.com/MVIG-SJTU/AlphAction/issues/1#issuecomment-623856702).  Best deployed on a workstation.

**Comment by athulvingt** [comment]
> Sorry, we only plan to support GPU for this project. The computation cost could be much heavy for CPU devices or even laptops with a nvidia GPU (see [#1 (comment)](https://github.com/MVIG-SJTU/AlphAction/issues/1#issuecomment-623856702)). Best deployed on a workstation.

you meant just training the model or inference as well?
