### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lingjun-1996** [MVIG-SJTU/AlphAction#41]
python: 3.7.1
ninja: 1.7.2
pytorch: 1.5.0
cudatoolkit:  10.2.89
torchvision:   0.6.0

When running the code 'pip install -e .' there is something error. 

Requirement already satisfied: PyYAML in c:\programdata\anaconda3\envs\py37action\lib\site-packages (from yacs->alphaction==0.0.0) (5.3.1)
Installing collected packages: alphaction
  Running setup.py develop for alphaction
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\py37action\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\IMAGEprocess\\program\\AlphAction-master\\setup.py'"'"'; __file__='"'"'D:\\IMAGEprocess\\program\\AlphAction-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:\IMAGEprocess\program\AlphAction-master\

 39 errors detected in the compilation of "C:/Users/LINGJU~1/AppData/Local/Temp/tmpxft_0000395c_00000000-10_SigmoidFocalLoss_cuda.cpp1.ii".
    SigmoidFocalLoss_cuda.cu
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
        check=True)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\subprocess.py", line 481, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\IMAGEprocess\program\AlphAction-master\setup.py", line 121, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
        build_ext.build_extensions(self)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
        with_cuda=with_cuda)
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "C:\ProgramData\Anaconda3\envs\py37action\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension

**Comment by yelantf** [comment]
Sorry, this project does not support Windows currently.
