### ISSUE TITLE
关于memory pool中mem_active标志位问题

### ISSUE THREAD

**Issue by chenhao-1115** [MVIG-SJTU/AlphAction#43]
很感谢您的开源行为，针对您提供的代码，我有以下两个问题希望得到您的回复：
问题描述：在trainer.py中我发现如果mem_active为False则不会进入memory的更新操作，我在cfg文件中将IA_STRUCTURE参数设置为True则会报以下错误：
Traceback (most recent call last):
  File "train_net.py", line 246, in <module>
    main()
  File "train_net.py", line 235, in main
    model = train(cfg, args.local_rank, args.distributed, tblogger, args.transfer_weight, args.adjust_lr, args.skip_val,args.no_head)
  File "train_net.py", line 58, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT, model_weight_only=transfer_weight,adjust_scheduler=adjust_lr, no_head=no_head)
  File "/home/mmsys8/disk/CH/Alphaction/AlphAction-master/alphaction/utils/checkpoint.py", line 61, in load
    self._load_model(checkpoint, no_head)
  File "/home/mmsys8/disk/CH/Alphaction/AlphAction-master/alphaction/utils/checkpoint.py", line 110, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"), no_head)
  File "/home/mmsys8/disk/CH/Alphaction/AlphAction-master/alphaction/utils/model_serialization.py", line 83, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/mmsys8/anaconda3/envs/alphaction/lib/python3.5/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ActionDetector:
        **size mismatch for roi_heads.action.feature_extractor.fc1.weight: copying a param with shape torch.Size([1024, 2304]) from checkpoint, the shape in current model is torch.Size([1024, 2816]).**
问题：
1.请问是不是如果mem_active标志位是False状态的话，就无法进行论文中AMU算法的实现？
2.请问我如何才能确保AMU算法的实现？应该如何设置参数才能使得以上错误被修正？

再次感谢您的工作，期待您的回复。

**Comment by yelantf** [comment]
1. `mem_active=False` means that we do not use memory features in the IA structure. Since we do not use memory features, there is nowhere to apply AMU algorithm.
2. Just set `mem_active=True`, you could use AMU algorithm with memory features. The error you reported seems to be a miss matching of weight size, which means that you are using a wrong weight file to initialize your model. If you do not want to use memory features, you should use a pre-trained model without memory features either.

**Comment by yelantf** [comment]
Issue closed due to the lack of response.
