### ISSUE TITLE
在Centos 7 下一切安装就绪，在运行demo时报以下错误，请大神帮忙看一下

### ISSUE THREAD

**Issue by baigang666** [MVIG-SJTU/AlphAction#51]
使用CPU的时候报以下错误：

Loading action model weight from ../data/models/aia_models/resnet50_4x16f_baseline.pth.
Action model weight successfully loaded.
Loading tracking model..
Network successfully loaded
Showing tracking progress bar (in fps). Other processes are running in the background.
Tracker Progress: 66 frame [00:57,  1.06s/ frame]Process Process-4:
Traceback (most recent call last):
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/A100-bg/Source_File/AlphAction/demo/action_predictor.py", line 433, in _compute_prediction
    transform_randoms)
  File "/home/A100-bg/Source_File/AlphAction/demo/action_predictor.py", line 129, in update_feature
    feature = self.model(slow_clips, fast_clips, boxes, objects, part_forward=0)
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/modeling/detector/action_detector.py", line 25, in forward
    result, detector_losses, loss_weight, detector_metrics = self.roi_heads(slow_features, fast_features, boxes, objects, extras, part_forward)
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/modeling/roi_heads/roi_heads_3d.py", line 12, in forward
    result, loss_action, loss_weight, accuracy_action = self.action(slow_features, fast_features, boxes, objects, extras, part_forward)
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/modeling/roi_heads/action_head/action_head.py", line 41, in forward
    x, x_pooled, x_objects = self.feature_extractor(slow_features, fast_features, proposals, objects, extras, part_forward)
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/modeling/roi_heads/action_head/roi_action_feature_extractor.py", line 83, in forward
    x = self.roi_pooling(slow_features, fast_features, proposals)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/modeling/roi_heads/action_head/roi_action_feature_extractor.py", line 49, in roi_pooling
    slow_x = self.pooler(slow_features, proposals)
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/modeling/poolers.py", line 39, in forward
    return self.pooler(x, rois)
  File "/home/A100-bg/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/A100-bg/Source_File/AlphAction/alphaction/layers/roi_align_3d.py", line 59, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio
  File "/home/A100-bg/Source_File/AlphAction/alphaction/layers/roi_align_3d.py", line 19, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio
RuntimeError: Not implemented on the CPU
难道是模型不支持CPU？

**Comment by irvingzhang0512** [comment]
不支持CPU #2

**Comment by Krystal0606** [comment]
大佬编译的时候有遇到错误吗？
