### ISSUE TITLE
ubuntu18.04  There was a problem when running the demo

### ISSUE THREAD

**Issue by shenshixinglt1528** [MVIG-SJTU/AlphAction#66]
root@jy-pytorch-env-67596d5c7c-64vm2:/workspace/AlphAction-master/demo# CUDA_VISIBLE_DEVICES=5 python demo.py --video-path input001.mp4 --output-path path/data/output --cfg-path /workspace/AlphAction-master/config_files/resnet101_8x8f_denseserial.yaml --weight-path /workspace/AlphAction-master/data/models/aia_models/resnet101_8x8f_denseserial.pth
Starting video demo, video path: input001.mp4
Warning: The detected frame rate 0.0 could be wrong. The behavior of this demo code can be abnormal.
[ERROR:0] global /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap.cpp (587) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.2) /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): path/data/output in function 'icvExtractPattern'

Loading action model weight from /workspace/AlphAction-master/data/models/aia_models/resnet101_8x8f_denseserial.pth.
Action model weight successfully loaded.
Loading YOLO model..
Network successfully loaded
Loading tracking model..
Network successfully loaded
Traceback (most recent call last):
  File "demo.py", line 194, in <module>
    main()
  File "demo.py", line 143, in main
    ava_predictor_worker = AVAPredictorWorker(args)
  File "/workspace/AlphAction-master/demo/action_predictor.py", line 267, in __init__
    det_loader = VideoDetectionLoader(cfg, self.track_queue, self.input_queue, self.predictor_process)
  File "/workspace/AlphAction-master/demo/video_detection_loader.py", line 64, in __init__
    assert stream.isOpened(), 'Cannot capture source'
AssertionError: Cannot capture source

**Comment by Hugo-cheng** [comment]
你好 能不能分享一下你的权重文件

**Comment by yan-ctrl** [comment]
> root@jy-pytorch-env-67596d5c7c-64vm2:/workspace/AlphAction-master/demo# CUDA_VISIBLE_DEVICES=5 python demo.py --video-path input001.mp4 --output-path path/data/output --cfg-path /workspace/AlphAction-master/config_files/resnet101_8x8f_denseserial.yaml --weight-path /workspace/AlphAction-master/data/models/aia_models/resnet101_8x8f_denseserial.pth Starting video demo, video path: input001.mp4 Warning: The detected frame rate 0.0 could be wrong. The behavior of this demo code can be abnormal. [ERROR:0] global /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap.cpp (587) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
> 
> OpenCV(4.5.2) /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): path/data/output in function 'icvExtractPattern'
> 
> Loading action model weight from /workspace/AlphAction-master/data/models/aia_models/resnet101_8x8f_denseserial.pth. Action model weight successfully loaded. Loading YOLO model.. Network successfully loaded Loading tracking model.. Network successfully loaded Traceback (most recent call last): File "demo.py", line 194, in main() File "demo.py", line 143, in main ava_predictor_worker = AVAPredictorWorker(args) File "/workspace/AlphAction-master/demo/action_predictor.py", line 267, in **init** det_loader = VideoDetectionLoader(cfg, self.track_queue, self.input_queue, self.predictor_process) File "/workspace/AlphAction-master/demo/video_detection_loader.py", line 64, in **init** assert stream.isOpened(), 'Cannot capture source' AssertionError: Cannot capture source



> root@jy-pytorch-env-67596d5c7c-64vm2:/workspace/AlphAction-master/demo# CUDA_VISIBLE_DEVICES=5 python demo.py --video-path input001.mp4 --output-path path/data/output --cfg-path /workspace/AlphAction-master/config_files/resnet101_8x8f_denseserial.yaml --weight-path /workspace/AlphAction-master/data/models/aia_models/resnet101_8x8f_denseserial.pth Starting video demo, video path: input001.mp4 Warning: The detected frame rate 0.0 could be wrong. The behavior of this demo code can be abnormal. [ERROR:0] global /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap.cpp (587) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
> 
> OpenCV(4.5.2) /tmp/pip-req-build-oxjbfc17/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): path/data/output in function 'icvExtractPattern'
> 
> Loading action model weight from /workspace/AlphAction-master/data/models/aia_models/resnet101_8x8f_denseserial.pth. Action model weight successfully loaded. Loading YOLO model.. Network successfully loaded Loading tracking model.. Network successfully loaded Traceback (most recent call last): File "demo.py", line 194, in main() File "demo.py", line 143, in main ava_predictor_worker = AVAPredictorWorker(args) File "/workspace/AlphAction-master/demo/action_predictor.py", line 267, in **init** det_loader = VideoDetectionLoader(cfg, self.track_queue, self.input_queue, self.predictor_process) File "/workspace/AlphAction-master/demo/video_detection_loader.py", line 64, in **init** assert stream.isOpened(), 'Cannot capture source' AssertionError: Cannot capture source

Have you solved it? Can you tell me how to solve it?
