### ISSUE TITLE
Getting error while using pip install -e .

### ISSUE THREAD

**Issue by pordeli** [MVIG-SJTU/AlphAction#71]
Hi. I have cuda 10.2 and installed pytorch with cuda 10.2 but get below error: How to solve it? What is the issue?

(alphaction1) s438763@hcc3:/data/Sahar5/AlphAction-master$ python -c 'from torch.utils.collect_env import main; main()'
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 450.119.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h497a2fe_0    conda-forge
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.20.3           py38hf144106_0  
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] torchvision               0.10.0               py38_cu102    pytorch
(alphaction1) s438763@hcc3:/data/Sahar5/AlphAction-master$ (nvcc --version | grep -oP '(?<=release )[\d\.]*?(?=,)')
10.2

Installing collected packages: alphaction
  Running setup.py develop for alphaction
    ERROR: Command errored out with exit status 1:
     command: /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/Sahar5/AlphAction-master/setup.py'"'"'; __file__='"'"'/data/Sahar5/AlphAction-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /data/Sahar5/AlphAction-master/
    Complete output (106 lines):
    running develop
    running egg_info
    writing alphaction.egg-info/PKG-INFO
    writing dependency_links to alphaction.egg-info/dependency_links.txt
    writing requirements to alphaction.egg-info/requires.txt
    writing top-level names to alphaction.egg-info/top_level.txt
    reading manifest file 'alphaction.egg-info/SOURCES.txt'
    writing manifest file 'alphaction.egg-info/SOURCES.txt'
    running build_ext
    building 'alphaction._custom_cuda_ext' extension
    creating /data/Sahar5/AlphAction-master/build
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc
    creating /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda
    Emitting ninja build file /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/5] /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIAlign3d_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIAlign3d_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIAlign3d_cuda.o
    /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIAlign3d_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIAlign3d_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Path to libdevice library not specified
    [2/5] /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SoftmaxFocalLoss_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SoftmaxFocalLoss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SoftmaxFocalLoss_cuda.o
    /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SoftmaxFocalLoss_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SoftmaxFocalLoss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Path to libdevice library not specified
    [3/5] /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIPool3d_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIPool3d_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIPool3d_cuda.o
    /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIPool3d_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/ROIPool3d_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Path to libdevice library not specified
    [4/5] /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.o
    /usr/bin/nvcc  -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Path to libdevice library not specified
    [5/5] c++ -MMD -MF /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/vision.o.d -pthread -B /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/data/Sahar5/AlphAction-master/alphaction/csrc -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/TH -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/THC -I/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/include/python3.8 -c -c /data/Sahar5/AlphAction-master/alphaction/csrc/vision.cpp -o /data/Sahar5/AlphAction-master/build/temp.linux-x86_64-3.8/data/Sahar5/AlphAction-master/alphaction/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140:0,
                     from /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                     from /data/Sahar5/AlphAction-master/alphaction/csrc/cpu/vision.h:2,
                     from /data/Sahar5/AlphAction-master/alphaction/csrc/ROIAlign3d.h:3,
                     from /data/Sahar5/AlphAction-master/alphaction/csrc/vision.cpp:1:
    /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)
    
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
        subprocess.run(
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/Sahar5/AlphAction-master/setup.py", line 103, in <module>
        setup(
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/UCSTAFF.WIN.CANBERRA.EDU.AU/s438763/anaconda3/envs/alphaction1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/Sahar5/AlphAction-master/setup.py'"'"'; __file__='"'"'/data/Sahar5/AlphAction-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by sainivedh** [comment]
Hi, Have you resolved the error ?!

Thanks
