### ISSUE TITLE
TypeError: conv3d() received an invalid combination of arguments

### ISSUE THREAD

**Issue by changsubi** [MVIG-SJTU/AlphAction#81]
The following error occurred while running the demo.

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/csyun/AlphAction-master/demo/action_predictor.py", line 365, in _compute_prediction
    predictions = self.ava_predictor.compute_prediction(feature_index, video_size)
  File "/home/csyun/AlphAction-master/demo/action_predictor.py", line 218, in compute_prediction
    output = self.model(None, None, None, None, extras=extras, part_forward=1)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/csyun/AlphAction-master/alphaction/modeling/detector/action_detector.py", line 25, in forward
    result, detector_losses, loss_weight, detector_metrics = self.roi_heads(slow_features, fast_features, boxes, objects, extras, part_forward)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/csyun/AlphAction-master/alphaction/modeling/roi_heads/roi_heads_3d.py", line 12, in forward
    result, loss_action, loss_weight, accuracy_action = self.action(slow_features, fast_features, boxes, objects, extras, part_forward)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/csyun/AlphAction-master/alphaction/modeling/roi_heads/action_head/action_head.py", line 41, in forward
    x, x_pooled, x_objects = self.feature_extractor(slow_features, fast_features, proposals, objects, extras, part_forward)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/csyun/AlphAction-master/alphaction/modeling/roi_heads/action_head/roi_action_feature_extractor.py", line 107, in forward
    ia_feature = self.ia_structure(person_pooled, proposals, object_pooled, objects, memory_person, )
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/csyun/AlphAction-master/alphaction/modeling/roi_heads/action_head/IA_structure.py", line 169, in forward
    mem_feature)
  File "/home/csyun/AlphAction-master/alphaction/modeling/roi_heads/action_head/IA_structure.py", line 174, in _reduce_dim
    query = self.person_dim_reduce(person)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 590, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/csyun/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 586, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
TypeError: conv3d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)

How can I solve this?

**Comment by hejia-zhang** [comment]
I have the same problem, have you solved it?

**Comment by arqam-ai** [comment]
I have the same error for the input video duration longer than 1s, try inputting a video with duration 1s and see if you still have the error

**Comment by Seeseallllll** [comment]
I have the same problem, when using resnet101_8x8f_denseserial.yaml.
when I use other yaml (such as: --cfg-path '/AlphAction/config_files/resnet50_4x16f_baseline.yaml')  , this  problem does not happen.
I hope it will be helpful.

**Comment by SCUlsl** [comment]
I have meet the same error and have solved it.
It was caused by the padding which I set "zeros".When I set "None",it's nothing error happen

**Comment by 121649982** [comment]
> I have meet the same error and have solved it. It was caused by the padding which I set "zeros".When I set "None",it's nothing error happen

where to set it ?
