### ISSUE TITLE
Error while Training

### ISSUE THREAD

**Issue by RajKumarBiswokarma** [MVIG-SJTU/AlphAction#93]
Traceback (most recent call last):
  File "train_net.py", line 245, in <module>
    main()
  File "train_net.py", line 235, in main
    args.no_head)
  File "train_net.py", line 98, in train
    mem_active,
  File "/home/fm-pc-lt-269/Fuse/AlphAction/alphaction/engine/trainer.py", line 40, in do_train
    for iteration, (slow_video, fast_video, boxes, objects, extras, _) in enumerate(data_loader, start_iter):
  File "/home/fm-pc-lt-269/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/fm-pc-lt-269/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/fm-pc-lt-269/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/fm-pc-lt-269/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
  File "av/error.pyx", line 78, in av.error.FFmpegError.__init__
TypeError: __init__() takes at least 3 positional arguments (2 given)

**Comment by Young-eng** [comment]
have you solved it ? I got the same error. Thanks!
