### ISSUE TITLE
 size mismatch

### ISSUE THREAD

**Issue by fengjingchehu** [MVIG-SJTU/AlphAction#95]
(alph) user@user-Super-Server:/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/AlphAction-master$ python demo/demo.py --video-path "demo/input/test4.avi" --output-path "demo/123" --cfg-path "./config_files/resnet101_8x8f_denseserial.yaml" --weight-path "./data/models/aia_models/resnet101_8x8f_denseserial.pth" --common-cate
Starting video demo, video path: demo/input/test4.avi
/home/user/anaconda3/envs/alph/lib/python3.8/site-packages/torch/nn/modules/container.py:552: UserWarning: Setting attributes on ParameterDict is not supported.
  warnings.warn("Setting attributes on ParameterDict is not supported.")
/home/user/anaconda3/envs/alph/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Loading action model weight from ./data/models/aia_models/resnet101_8x8f_denseserial.pth.
Traceback (most recent call last):
  File "demo/demo.py", line 194, in <module>
    main()
  File "demo/demo.py", line 143, in main
    ava_predictor_worker = AVAPredictorWorker(args)
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/AlphAction-master/demo/action_predictor.py", line 245, in __init__
    self.ava_predictor = AVAPredictor(
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/AlphAction-master/demo/action_predictor.py", line 70, in __init__
    _ = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/user/anaconda3/envs/alph/lib/python3.8/site-packages/alphaction-0.0.0-py3.8-linux-x86_64.egg/alphaction/utils/checkpoint.py", line 61, in load
    self._load_model(checkpoint, no_head)
  File "/home/user/anaconda3/envs/alph/lib/python3.8/site-packages/alphaction-0.0.0-py3.8-linux-x86_64.egg/alphaction/utils/checkpoint.py", line 110, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"), no_head)
  File "/home/user/anaconda3/envs/alph/lib/python3.8/site-packages/alphaction-0.0.0-py3.8-linux-x86_64.egg/alphaction/utils/model_serialization.py", line 83, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/user/anaconda3/envs/alph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ActionDetector:
        size mismatch for roi_heads.action.predictor.cls_score.weight: copying a param with shape torch.Size([80, 1024]) from checkpoint, the shape in current model is torch.Size([15, 1024]).
        size mismatch for roi_heads.action.predictor.cls_score.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([15]).

i wonder which size can i use and how ?

**Comment by tan2003IT** [comment]
同问，但不知道作者什么时候回复

**Comment by fengjingchehu** [comment]
> 同问，但不知道作者什么时候回复

好久了
